### ISSUE TITLE
Install on Lubuntu 14.04 - changing one line

### ISSUE THREAD

**Issue by divinemayhem** [boredland/spreadpi-upgrade#5]
Executing the script on a laptop running Lubuntu 14.04, I had to change one line. 

Line 149
was
sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so

changed to 
sudo ln -s /usr/lib/i386-linux-gnu/libturbojpeg.so.0.0.0 /usr/lib/i386-linux-gnu/libturbojpeg.so

**Comment by boredland** [comment]
I think the best would be to make that case sensitive either one is running
on i386, x86 or armhf etc. Will do that tomorrow if I have spare time.
Am 27.02.2015 17:43 schrieb "divinemayhem" notifications@github.com:

**Comment by boredland** [comment]
Can you please post me the output for `uname -i`

**Comment by boredland** [comment]
has been solved bulky...
